<a href="https://colab.research.google.com/github/rafaeldjsm/Matematica/blob/main/caminhoab_diag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema do rato no labirinto.

## Neste caso vamos considerar um problema alternativo em que é possível a locomoção nas casas horizontais, verticais e diagonais.

Ajude um rato a encontrar um pedaço de queijo num labirinto como o do desenho da figura 1: Um labirinto desses pode ser representado por uma matriz retangular L, cujo elemento $L[i][j]$ vale 0 ou −1 conforme a casa correspondente do labirinto seja uma passagem livre ou uma parede, respectivamente.

<center>
<img src ='https://raw.githubusercontent.com/rafaeldjsm/Matematica/master/imagens/rato_labirinto.PNG' width=500px>
</center>

## Saída de Dados 

A saída do seu programa deve ser uma lista de coordenadas que comece pela posição inicial do rato e termine na posição inicial do queijo. Essa sequencia de coordenadas deve indicar o caminho mais curto para o rato chegar ao queijo.

In [ ]:
import numpy as np

def matab():
    l = []
    for i in range(6):
        li = []
        for j in range(11):
            if [i,j] in [[0,2],[0,3],
                         [1,1],[1,4],[1,6],[1,8],[1,9],
                         [2,2],[2,4],[2,6],[2,10],
                         [3,1],[3,3],[3,7],[3,8],
                         [4,3],[4,5],[4,9],
                         [5,1],[5,8]]:
                li.append(-1)
            else:
                li.append(0)
        l.append(li)
    return np.array(l)

In [ ]:
b = [5,10]
a = [0,0]

mat0 = matab().copy()
mat0

array([[ 0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0, -1,  0, -1,  0, -1, -1,  0],
       [ 0,  0, -1,  0, -1,  0, -1,  0,  0,  0, -1],
       [ 0, -1,  0, -1,  0,  0,  0, -1, -1,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0,  0,  0, -1,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0]])

In [ ]:
lm1,cm1 = np.where(mat0 == -1)

In [ ]:
def vizinhos(x,y):
    l = [[x-1,y-1],[x-1,y],[x-1,y+1],[x,y-1],[x,y+1],[x+1,y-1],[x+1,y],[x+1,y+1]]
    lr = [k for k in l if k[0] >= 0 and k[1] >= 0]
    return lr


def wayab(mat0,a,b):
    mat = mat0.copy()
    li,co = mat.shape
    b0,b1 = b
    a0,a1 = a
    mat[b0][b1] = 1

    c0,c1 = b
    cnt = 1
    strt = 0 #start da lista de vizinhos

    lm1,cm1 = np.where(mat0 == -1)
    imped = [[k,j] for k,j in zip(lm1,cm1)]
    ult = []

    while (c0,c1) != (a0,a1) and cnt < 30:
        ult = imped.copy()+ ult + [[c0,c1]]
        viz = vizinhos(c0,c1)
        l = np.array([mat[k,j] for k,j in viz if (k <= li-1 and j <= co-1 and [k,j] not in ult)])
        lidx = [[k,j] for k,j in viz if (k <= li-1 and j <= co-1 and [k,j] not in ult)]
        ll = len(lidx)
        
        if ll == 0:
            imped.append([c0,c1])
            ult = []
            c0,c1 = b
            cnt = 1
            strt += 1 
        else:
            c0,c1 = lidx[strt % ll]
            cnt+=1
            mat[c0,c1] = cnt
    print(mat)

In [ ]:
wayab(mat0,a,b)

[[12 11 -1 -1  8  7  6  0  0  0  0]
 [ 0 -1 10  9 -1  0 -1  5 -1 -1  0]
 [ 0  0 -1  0 -1  0 -1  0  4  0 -1]
 [ 0 -1  0 -1  0  0  0 -1 -1  3  0]
 [ 0  0  0 -1  0 -1  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0 -1  0  1]]
